export const trips = [
  {
    slug: "sammed-shikharji-yatra",
    title: "Sammed Shikharji Yatra",
    category: "pilgrimage",
    routeSummary: "Delhi → Deoghar → Madhuban",
    durationDays: 4,
    durationNights: 3,
    basePrice: 33999,
    images: [] as string[],
    careFeatures: [
      "BP & sugar monitoring twice daily",
      "Verified Saathi companion",
      "9 Tonks assisted darshan",
      "Medical attendant on route",
    ],
    inclusions: [
      "Jain Satvik Meals",
      "Bike Trek Assist",
      "Medical Attendant · Oxygen Cylinder",
      "Live WhatsApp Family Updates",
    ],
    summary:
      "A 4-day, 3-night assisted pilgrimage to the Sammed Shikharji Jain Tirtha, with companion support across all 9 Tonks.",
    days: [
      {
        dayNumber: 1,
        title: "Delhi → Deoghar",
        description: "Departure from Delhi, arrival and rest in Deoghar ahead of the yatra.",
        activities: ["Morning departure", "Evening arrival in Deoghar", "Health check-in and briefing"],
      },
      {
        dayNumber: 2,
        title: "Deoghar → Madhuban",
        description: "Transfer to Madhuban, the base for the Shikharji ascent.",
        activities: ["Assisted transfer", "Rest and acclimatization", "Route briefing for the Tonk circuit"],
      },
      {
        dayNumber: 3,
        title: "Assisted Tonk darshan",
        description: "Guided, paced darshan across the 9 Tonks with companion and medical support.",
        activities: ["Early departure with companion", "Assisted darshan at multiple Tonks", "Return to Madhuban, evening health check-in"],
      },
      {
        dayNumber: 4,
        title: "Madhuban → Delhi",
        description: "Return journey with a final family health summary shared on arrival.",
        activities: ["Morning check-out", "Return travel to Delhi", "Family notified of safe return"],
      },
    ],
  },
  {
    slug: "dwarka-rann-of-kutch",
    title: "Dwarka + Rann of Kutch Spiritual & Heritage Yatra",
    category: "pilgrimage",
    routeSummary: "Ahmedabad → Dwarka → Beyt Dwarka → Shivrajpur → Mundra → Rann of Kutch → Ahmedabad",
    durationDays: 7,
    durationNights: 6,
    basePrice: 48000,
    images: [] as string[],
    careFeatures: [
      "Assisted boat boarding with life jackets",
      "Wheelchair access paths at White Rann",
      "Medical checks and hydration reminders",
      "Minimal walking, vehicle-based sightseeing",
    ],
    inclusions: [
      "Senior-friendly hotels with lifts",
      "Assisted darshan at all temple stops",
      "Bus-based Adani Port orientation",
      "Cultural folk music evenings",
    ],
    summary:
      "From Krishna's Dwarka to the White Rann — a 7-day, 6-night journey of devotion, heritage, and modern India, paced for ages 45-95.",
    days: [
      { dayNumber: 1, title: "Ahmedabad → Dwarka", description: "Arrival and settling, evening Gomti Ghat aarti viewing (seated).", activities: ["Morning pickup from Ahmedabad", "Comfortable transfer with rest stops", "Evening Gomti Ghat visit", "Early dinner and rest"] },
      { dayNumber: 2, title: "Dwarka Temple Circuit", description: "Assisted darshan block with walking kept minimal throughout.", activities: ["Dwarkadhish Temple priority senior darshan", "Rukmini Devi Temple", "Optional Gita Mandir or Swaminarayan Mandir evening visit"] },
      { dayNumber: 3, title: "Nageshwar Jyotirlinga → Beyt Dwarka → Shivrajpur", description: "Jyotirlinga darshan combined with Mahabharata-linked Beyt Dwarka and a beach sunset stop.", activities: ["Nageshwar Jyotirlinga, flat access", "Assisted boat crossing to Beyt Dwarka", "Sunset at Shivrajpur Beach, wheelchairs available"] },
      { dayNumber: 4, title: "Dwarka → Mundra (Adani Port)", description: "A bus-based, no-walking-required orientation of India's modern maritime infrastructure.", activities: ["Late breakfast and relaxed drive", "Guided Adani Port viewing from the bus", "Early dinner"] },
      { dayNumber: 5, title: "Mundra → Bhuj → Rann of Kutch", description: "Crafts village visit followed by a wheelchair-accessible White Rann sunset.", activities: ["Bhuj crafts village, seated demonstrations", "White Rann sunset visit", "Seated cultural folk music"] },
      { dayNumber: 6, title: "Rann of Kutch → Bhuj", description: "A leisure and culture day with optional temple visit and assisted shopping.", activities: ["Late wake-up", "Optional local temple visit", "Assisted handicraft shopping"] },
      { dayNumber: 7, title: "Bhuj → Ahmedabad", description: "Comfortable return journey with assisted drop-offs.", activities: ["Comfortable return drive", "Assisted drop-offs", "Family notified of safe return"] },
    ],
  },
  {
    slug: "char-dham-yatra",
    title: "Char Dham Yatra — Fully Assisted",
    category: "pilgrimage",
    routeSummary: "Yamunotri → Gangotri → Kedarnath → Badrinath",
    durationDays: 11,
    durationNights: 10,
    basePrice: 52999,
    images: [] as string[],
    careFeatures: ["Wheelchair & porter support", "Daily health vitals check", "Dedicated MITRAM Saathi companion"],
    inclusions: ["4 Star Hotels", "AC Transport", "All Meals", "Flight options available"],
    summary: "The complete Char Dham circuit, fully assisted for senior travelers with daily health monitoring.",
    days: [] as { dayNumber: number; title: string; description: string; activities: string[] }[],
  },
  {
    slug: "vaishno-devi-yatra",
    title: "Vaishno Devi Yatra",
    category: "pilgrimage",
    routeSummary: "Delhi → Jammu → Katra",
    durationDays: 6,
    durationNights: 5,
    basePrice: 28999,
    images: [] as string[],
    careFeatures: ["Medical kit on route", "Live GPS family updates"],
    inclusions: ["Pony / Pittu option", "Hotel", "All meals", "Train options available"],
    summary: "A dignity-paced Vaishno Devi pilgrimage with pony/palanquin assistance and live family updates.",
    days: [] as { dayNumber: number; title: string; description: string; activities: string[] }[],
  },
  {
    slug: "jannat-e-kashmir-vistadome",
    title: "Jannat-e-Kashmir by Vistadome Train",
    category: "heritage",
    routeSummary: "Delhi → Udhampur → Srinagar",
    durationDays: 8,
    durationNights: 7,
    basePrice: 44999,
    images: [] as string[],
    careFeatures: ["Altitude medical support", "Slow-paced itinerary"],
    inclusions: ["Vistadome train", "Houseboat stay", "Dal Lake", "All meals", "Airport transfers"],
    summary: "A scenic, slow-paced Kashmir journey by Vistadome train, houseboat, and Dal Lake.",
    days: [] as { dayNumber: number; title: string; description: string; activities: string[] }[],
  },
  {
    slug: "maharashtra-jyotirlinga-circuit",
    title: "Maharashtra Jyotirlinga Circuit",
    category: "pilgrimage",
    routeSummary: "Mumbai → Trimbakeshwar → Grishneshwar → Shirdi → Bhimashankar → Pune → Mumbai",
    durationDays: 7,
    durationNights: 6,
    basePrice: 39999,
    images: [] as string[],
    careFeatures: [
      "1 MITRAM Coordinator for every 8 seniors",
      "Wheelchairs, first-aid, motion-sickness kits, BP/sugar checks",
      "Emergency escalation plan and insurance guidance",
    ],
    inclusions: ["AC low-step coach with attendant", "3-star senior-friendly hotels", "All breakfasts plus 4 prepaid meals", "MITRAM Live Tracker"],
    summary: "Four Jyotirlingas and Shirdi's Sai Baba, at a slow, assisted, dignity-first pace with no overnight drives.",
    days: [
      { dayNumber: 1, title: "Mumbai → Nashik", description: "Scenic drive via Kasara Ghat with a mid-morning breakfast stop.", activities: ["Home pickups across Mumbai", "Breakfast stop at Shahapur", "Hotel check-in and mandatory rest"] },
      { dayNumber: 2, title: "Trimbakeshwar Jyotirlinga & Godavari Aarti", description: "Assisted darshan at one of the 12 Jyotirlingas, at the source of the Godavari.", activities: ["Assisted Trimbakeshwar darshan and Rudrabhishek", "Optional Brahmagiri viewpoint", "Seated Godavari Aarti"] },
      { dayNumber: 3, title: "Nashik → Aurangabad", description: "Comfortable travel day with extra rest breaks.", activities: ["Depart Nashik", "Lunch en route", "Evening rest and briefing in Aurangabad"] },
      { dayNumber: 4, title: "Grishneshwar Jyotirlinga → Shirdi", description: "The final Jyotirlinga, followed by transfer to Shirdi.", activities: ["Assisted Grishneshwar darshan", "Optional flat-area Ellora highlights", "Drive to Shirdi with rest breaks"] },
      { dayNumber: 5, title: "Shirdi Sai Baba — full darshan and rest day", description: "A full day at Shirdi with assisted darshan and an evening satsang.", activities: ["Assisted Sai Baba darshan", "Dwarkamai and Chavadi visit", "Evening aarti and bhajan"] },
      { dayNumber: 6, title: "Shirdi → Bhimashankar → Pune", description: "Assisted darshan at the forest-set Bhimashankar Jyotirlinga, then on to Pune.", activities: ["Morning drive with breaks", "Assisted Bhimashankar darshan", "Celebration dinner in Pune"] },
      { dayNumber: 7, title: "Pune → Mumbai", description: "Return journey with a final family health summary.", activities: ["Breakfast and check-out", "Return drive with lunch stop", "Home drop-offs across Mumbai"] },
    ],
  },
];

export const internationalTrips = [
  { slug: "bhutan-gentle-himalaya", title: "Bhutan — Gentle Himalaya", category: "international", routeSummary: "Paro → Thimphu → Punakha", durationDays: 6, durationNights: 5, basePrice: 89999, images: [] as string[], careFeatures: ["Low-altitude itinerary", "Oxygen support on standby"], inclusions: ["Visa assistance", "All meals", "AC transport"], summary: "A gentle, low-altitude introduction to Bhutan's monasteries and valleys.", days: [] as { dayNumber: number; title: string; description: string; activities: string[] }[] },
  { slug: "spain-portugal-heritage", title: "Spain & Portugal Heritage", category: "international", routeSummary: "Madrid → Lisbon → Porto", durationDays: 10, durationNights: 9, basePrice: 189999, images: [] as string[], careFeatures: ["English/Hindi-speaking coordinator", "Wheelchair-accessible coach"], inclusions: ["4-star hotels", "Daily breakfast", "Guided heritage tours"], summary: "Iberian heritage at a relaxed, senior-friendly pace.", days: [] as { dayNumber: number; title: string; description: string; activities: string[] }[] },
];
